export const GET_REQUEST="GET_REQUEST";
export const GET_ERROR="GET_ERROR";
export const GET_SUCCESS="GET_SUCCESS";

export const GET_SORTED_REQUEST="GET_SORTED_REQUEST";
export const GET_SORTED_ERROR="GET_SORTED_ERROR";
export const GET_SORTED_SUCCESS="GET_SORTED_SUCCESS";
